export const TITLE_BG = 'transparent'
export const GET_TICKETS_BG = 'transparent'
export const CHECK_PRIZES_BG = 'transparent'
export const FINISHED_ROUNDS_BG = 'transparent'
export const FINISHED_ROUNDS_BG_DARK = 'transparent'
